Bugfix: do not ignore agentCheckinInterval
rancher/fleet pull request #1058
Opened 2022-10-26 10:30 UTC by moio

Signed-off-by: Silvio Moioli <silvio@moioli.net>

Fixes #1057 

A typo in a configuration parameter name prevented it from being correctly applied. rancher/rancher seems not to be affected (a grep search only surfaces the correct parameter name), so this might only affect standalone installations.

## Test

See reproduction steps in https://github.com/rancher/fleet/issues/1057

I tested this manually.

## Additional Information

### Tradeoff

Keeping the old name around and use it if defined. From my understanding nobody really used it so far.

### Potential improvement

None.

2022-10-27 07:58 UTC, moio commented
@manno, @thardeck: what are your feelings about testing this patch?

I tested this manually in my setup, and expect to soon have at least a user independently testing it too. Do we want any sort of automated test?

 - `go test`: I do not see a good way to test this
 - e2e tests: it's a possibility to add this parameter as an extra `--set agentCheckinInterval=21s` here:

https://github.com/rancher/fleet/blob/e2e4b564690287708870084781177dfcd91a78dc/.github/scripts/deploy-fleet.sh#L19-L25

and then check that the value is correct in the agent's deployment, something conceptually similar to:

```sh
~ kubectl get --namespace=$NAMESPACE deployment fleet-agent --output=yaml | grep -A1 CHECKIN_INTERVAL
        - name: CHECKIN_INTERVAL
          value: 21s
```

(I chose the value of 21s for illustration purposes only)

It's probably not a test with a terribly good future breakage predicting power - I'd leave it up to you decide whether it's worth the code or not. Or maybe you have better ideas 😉

2022-10-27 09:50 UTC, manno requested changes

2022-10-27 09:50 UTC, manno commented on pkg/config/config.go
> +	AgentCheckinInterval            metav1.Duration   `json:"AgentCheckinInterval,omitempty"`
```suggestion
	AgentCheckinInterval            metav1.Duration   `json:"agentCheckinInterval,omitempty"`
```

2022-10-27 09:58 UTC, manno commented
> @manno, @thardeck: what are your feelings about testing this patch?

> I tested this manually in my setup, and expect to soon have at least a user independently testing it too. Do we want any sort of automated test?

Not needed right now.  Long term we could look into https://github.com/helm/chart-testing (example: https://github.com/epinio/helm-charts/blob/main/.github/workflows/main-ci.yml#L46-L52).

In general it depends if you want to test the chart, or the CLI, or both in an acceptance/e2e test. However, the helm arguments are not documented and we don't really support standalone/helm use. (well, we use it for testing, so it's very supported in a way)

2022-10-27 11:03 UTC, moio commented
Thanks @manno, I tend to agree with your perspective. I would proceed merging this as soon as we have user positive feedback, unless you have any other objection.

2022-11-03 10:44 UTC, moio commented
@manno Just rebased, positive feedback from user, I'd merge unless you have any reasons not to.

2022-11-04 09:32 UTC, manno approved these changes

2022-11-04 09:35 UTC, merged