Reading contents&secrets uses specific service account
rancher/fleet pull request #1063
Opened 2022-10-28 14:57 UTC by manno

2022-11-03 08:41 UTC, thardeck commented
> Fixes #853 by moving the two roles onto specific service accounts.

The issue reference seems to be wrong. It refers to #853

2022-11-03 13:10 UTC, manno commented
> > Fixes #853 by moving the two roles onto specific service accounts.
> 
> The issue reference seems to be wrong.

Thanks, it was  in https://github.com/rancherlabs/rancher-security

2022-11-03 13:18 UTC, thardeck requested changes

2022-11-03 13:18 UTC, thardeck commented on e2e/installation/verify_test.go
> +			output := path.Join(tmpdir, testenv.RandomFilename("manifests.yaml"))
I would use a more fitting variable name like `file` or `filePath`.

2022-11-03 14:40 UTC, thardeck approved these changes

2022-11-03 14:41 UTC, merged

2022-11-18 09:41 UTC, manno commented
@rancher/qa

## Additionnal QA
### Issue: https://github.com/rancherlabs/rancher-security/issues/853

### Problem
After installation Fleet did not pass hardening validation.

### Solution

Two roles were moved to specific service accounts. These service accounts are already created per cluster.
 
### Testing

Install fleet, harden the cluster by [removing default tokens from the service accounts](https://docs.ranchermanager.rancher.io/v2.5/reference-guides/rancher-security/rancher-v2.5-hardening-guides/hardening-guide-with-cis-v1.6-benchmark#set-automountserviceaccounttoken-to-false-for-default-service-accounts).

Run the [script](https://github.com/rancher/security-scan/blob/fd39c51fd16e522815f244069b497e060e8c5f9c/package/helper_scripts/check_for_default_sa.sh) to verify no roles are bound to the default service accounts.

### Engineering Testing
#### Manual Testing

* Fleet can still deploy
* started documenting the registration flow

#### Automated Testing

* no new tests

### QA Testing Considerations

Since an upgrade wouldn't modify the dynamically created roles, the old permissions should still be in place. Only new fleet installations benefit from the stricter role bindings.
 
#### Regressions Considerations

Fleet creates a lot of rbac resources dynamically, i.e. per cluster, during the registration process, .... This is hard to audit.