Remove obsolete Github Action cron jobs
rancher/fleet pull request #1562
Opened 2023-05-31 06:16 UTC by thardeck

there should be no gain in the cron runs since they are already executed against each new pr.

2023-05-31 06:43 UTC, weyfonk submitted a review, later dismissed
LGTM :)

2023-05-31 06:52 UTC, olblak commented
> there should be no gain in the cron runs since they are already executed against each new pr.

I am curious, what's the motivation? Are you solving a specific problem?

2023-05-31 08:24 UTC, manno requested changes

2023-05-31 08:24 UTC, manno commented on .github/workflows/ci.yml
> -  schedule:
This workflow runs unit and integration tests.

2023-05-31 08:24 UTC, manno commented on .github/workflows/golangci-lint.yml
> -    - cron:  '0 5 * * *'
This workflow only shows *all* issues if run on schedule.

```
only-new-issues: "${{ github.event_name == 'pull_request'}}"
```

2023-06-01 14:49 UTC, manno commented on .github/workflows/ci.yml
> -  schedule:
But could turn red because of external dependencies, which we wouldn't notice in periods with little or no PRs.

2023-06-01 14:50 UTC, manno commented on .github/workflows/golangci-lint.yml
> -    - cron:  '0 5 * * *'
Updates to the linters could quickly change this situation.

2023-06-01 14:54 UTC, closed without merging