Document public API
rancher/fleet pull request #1639
Opened 2023-07-07 12:58 UTC by manno

Fix #1555

2023-09-06 13:21 UTC, weyfonk requested changes
Impressive work, thanks!
Please don't be scared by the large number of comments, which are mostly nitpicks. This is a great effort.
As we have a few structs which are not meant to be used outside Fleet, should we consider moving them to (a) different package(s)?

2023-09-06 15:55 UTC, manno commented on pkg/apis/fleet.cattle.io/v1alpha1/bundle.go
> +	// JSONPointers is normally empty.
Ah, found this:
> // JSONPointers ignore diffs at a certain JSON path

```
    jsonPointers:
    - "/webhooks"
```

2023-09-06 16:38 UTC, manno commented on pkg/apis/fleet.cattle.io/v1alpha1/fleetyaml.go
> +	// modified per target. Targets are evaluated in order and the first
I thought it's a bundledeployment: `bundle+cluster=bundledeployment=target`. But you're right, the `target.go` file contains the cluster struct. Hmm.
 
Anyhow, I think together with the "first one to match a cluster is used for that cluster."  it's understandable.

2023-09-06 16:46 UTC, manno commented on pkg/apis/fleet.cattle.io/v1alpha1/git.go
> +	// IncompleteState is true if a bundle summary has 10 or more non-ready
Yes and not configurable. My other favorite is status.MaxNew=50 ... https://github.com/rancher/fleet/blob/document-public-crd-api/internal/cmd/controller/controllers/bundle/controller.go#L32

2023-09-06 16:48 UTC, manno commented on pkg/apis/fleet.cattle.io/v1alpha1/target.go
> +	// State is a summary state for the cluster group, calculated over the non-ready resources.
Changing this to "showing"?

2023-09-06 16:53 UTC, manno commented on pkg/apis/fleet.cattle.io/v1alpha1/target.go
> +// ClusterGroup is stored selector to target a group of clusters.
You could just use the selector in `targets:`, cluster groups have little functionality besides another aggregated status struct and that you don't have to repeat your target selector in different git repos.

2023-09-06 17:10 UTC, manno commented on pkg/apis/fleet.cattle.io/v1alpha1/target.go
> +	// false, it will trigger a migration. Old Fleet agents, don't have
Yes, it's more technical than user docs, but I find them confusing, so it's better to document something.

2023-09-07 13:54 UTC, weyfonk requested changes
Just one comment left on punctuation, sorry if my initial comment was not clear enough :)

2023-09-07 13:54 UTC, weyfonk commented on pkg/apis/fleet.cattle.io/v1alpha1/target.go
> +	// false, it will trigger a migration. Old Fleet agents, don't have
Fair enough.

2023-09-07 13:54 UTC, weyfonk commented on pkg/apis/fleet.cattle.io/v1alpha1/bundle.go
> +	// BundleDeploymentConditionReady will result in ErrApplied if false.
Oh I see, that makes much more sense than my interpretation. Thanks!

2023-09-08 06:57 UTC, manno commented
> Just one comment left on punctuation, sorry if my initial comment was not clear enough :)

Ah, I must have missed that comma.

2023-09-08 13:06 UTC, merged