adding 1903 image
rancher/fleet pull request #265
Opened 2021-02-04 23:05 UTC by luthermonson

2021-02-04 23:24 UTC, nickgerace requested changes
Need to add depends on for Windows and version to the manifest template.

```bash
[nickgerace at rancherbook in ~/Developer/rancher-fleet] (2) (master)
% grep -n 2004 manifest-agent.tmpl 
31:    image: rancher/fleet-agent:{{#if build.tag}}{{build.tag}}{{else}}{{replace "release/" "" build.branch }}-head{{/if}}-windows-amd64-2004
35:      version: 2004
[nickgerace at rancherbook in ~/Developer/rancher-fleet] (0) (master)
% grep -n 2004 .drone.yml 
350:name: windows-amd64-2004
354:  version: 2004
360:  image: luthermonson/drone-git:windows-2004-amd64
364:  image: luthermonson/drone-docker:2004
370:    tag: "${DRONE_TAG}-windows-amd64-2004"
374:      - "SERVERCORE_VERSION=2004"
489:- windows-amd64-2004
```

2021-02-04 23:39 UTC, nickgerace requested changes
I believe we are still missing depends on for the manifest section.

2021-02-05 21:28 UTC, nickgerace approved these changes

2021-02-05 21:30 UTC, StrongMonkey approved these changes

2021-02-05 21:31 UTC, merged