[Docs]Private helm docs
rancher/fleet pull request #334
Opened 2021-04-09 23:51 UTC by StrongMonkey

2021-04-10 00:36 UTC, nickgerace commented on docs/gitrepo-structure.md
> +    After secret is created, specify the secret to `gitRepo.spec.helmSecretName`. Make sure secret is created under the same namespace with gitrepo.
Is this supposed to be plaintext?
![image](https://user-images.githubusercontent.com/39320683/114252448-3ab28980-9973-11eb-8a5b-563a3c1d0214.png)

2021-04-10 00:49 UTC, nickgerace approved these changes
LGTM after seeing destination

2021-04-10 00:49 UTC, nickgerace commented on docs/gitrepo-structure.md
> +    After secret is created, specify the secret to `gitRepo.spec.helmSecretName`. Make sure secret is created under the same namespace with gitrepo.
explained offline that this isn't pure MD. resolving

2021-04-15 21:01 UTC, bmdepesa commented
Is it worth documenting that ssh keys with passphrase are not supported? I ran into this when testing.

2021-04-15 21:07 UTC, StrongMonkey commented
@bmdepesa That's a good point. I will get this documented.

2021-04-16 21:05 UTC, nickgerace approved these changes
LGTM after requested changes above

2021-04-20 23:06 UTC, catherineluse requested changes

2021-04-20 23:06 UTC, catherineluse commented on docs/gitrepo-add.md
> +  # If fleet.yaml contains private helm repo that requires autheticate,
> If fleet.yaml contains a private Helm repo that requires authentication,
 > provide the credentials in a K8s secret and specify them here. Details are provided
 > in the fleet.yaml documentation.

2021-04-20 23:06 UTC, catherineluse commented on docs/gitrepo-structure.md
> +    For private helm repo, user can reference a secret with the following key:
For a private Helm repo,

2021-04-20 23:08 UTC, catherineluse commented on docs/gitrepo-structure.md
> +    1. `username` and `password` for basic http auth if helm http repo is behind basic auth.
if the Helm HTTP repo is behind basic auth.

2021-04-20 23:08 UTC, catherineluse commented on docs/gitrepo-structure.md
> +    2. `cacerts` for custom CA bundle if helm repo is using custom CA.
if the Helm repo is using a custom CA.

2021-05-11 04:03 UTC, StrongMonkey commented
@catherineluse Can you review this again? Comment have been addressed. Need it to be merged :)

2021-05-11 12:33 UTC, catherineluse approved these changes

2021-05-11 16:02 UTC, merged