minor tweak to how values files are merged
rancher/fleet pull request #559
Opened 2021-10-13 01:13 UTC by ibrokethecloud

Minor tweak to how we are performing valuesFile merge when a helm options are being processed.

Related to: https://github.com/rancher/fleet/issues/416

A sample fleet.yaml referencing two values files:

```
namespace: default
helm:
  chart: ./demo
  valuesFiles:
    - values1.yaml
    - values2.yaml
targets:
- clusterSelector: {}
```

values1.yaml
```
microService1:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 256m
      memory: 256Mi

microService2:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 256m
      memory: 256Mi
```

and values2.yaml

```
microService1:
  replicas: 1
microService2:
  replicas: 2
```

Will now be rendered as

```
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: values-valuetest
  namespace: fleet-local
spec:
  helm:
    chart: ./demo
    values:
      microService1:
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 256m
            memory: 256Mi
      microService2:
        replicas: 2
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 256m
            memory: 256Mi
    valuesFiles:
    - values1.yaml
    - values2.yaml
 ```

2021-10-15 17:05 UTC, nickgerace requested changes
Will approve after change

2021-10-15 17:05 UTC, nickgerace commented on pkg/bundle/resources.go
> +
Delete this space

2021-10-16 06:12 UTC, ibrokethecloud commented on pkg/bundle/resources.go
> +
fixed it up

2021-10-16 06:59 UTC, ibrokethecloud commented
@StrongMonkey @nickgerace the CI seems to have failed on a windows build.

2021-10-19 15:09 UTC, merged