Add FOSSA to Drone Pipeline
rancher/fleet pull request #587
Opened 2021-11-01 14:28 UTC by oxr463

2021-11-01 16:25 UTC, nickgerace requested changes

2021-11-01 16:25 UTC, nickgerace commented on .drone.yml
> +  image: registry.suse.com/suse/sle15:15.3.17.8.1
This will need to be `registry.suse.com/suse/sle15:15.3` as discussed offline.

2021-11-01 21:48 UTC, nickgerace approved these changes

2021-11-01 21:49 UTC, nickgerace commented
@StrongMonkey I think we are good here with the image tag fixed. Thoughts?

2021-11-01 21:50 UTC, StrongMonkey commented
Looks good to me. Have we run this locally to see if it will succeed? I don't expect this to succeed though.

2021-11-02 19:07 UTC, oxr463 commented
> Looks good to me. Have we run this locally to see if it will succeed? I don't expect this to succeed though.

I've tested it locally without any issues. Please let me know if you need any assistance.

2021-11-02 19:13 UTC, StrongMonkey commented
@oxr463 Thanks, I am worried about breaking the pipeline without knowing how to fix it. Given it has been tested, LGTM!

2021-11-02 19:14 UTC, StrongMonkey approved these changes

2021-11-02 19:49 UTC, merged