Add troubleshooting section
rancher/fleet pull request #601
Opened 2021-11-09 08:07 UTC by papanito

Based on #595 I added a dedicate troubleshooting section. This is to collect different tips and trick which helps users and operators in case of troubles.

In addition I also separated the "Cluster and Bundles state" into a dedicate page. IMHO this is easier to find and hence can also be referenced from different pages if needed

2021-11-09 08:08 UTC, papanito commented
Please advice how I can review the rendering of the website before merging.

2021-11-11 16:25 UTC, catherineluse commented
If you clone the docs repo and run `./scripts/dev`, the docs website will build in a docker container.

2021-11-16 19:39 UTC, papanito commented
@nickgerace what do you think about this chance?

2021-11-16 20:55 UTC, nickgerace commented
I love the PR! We'll see if it fits into our docs well since @jtravee is doing work here in parallel. Thanks for the effort. I've added some reviewers.

2021-11-17 14:57 UTC, jtravee requested changes
Excellent ideas to create a new Troubleshooting section and adjust headers! Related issue #581.

2021-11-17 14:57 UTC, jtravee commented on docs/gitrepo-structure.md
> +see [Cluster and Bundle state](./cluster-bundles-state.md)
```suggestion
See [Cluster and Bundle state](./cluster-bundles-state.md).
```

2021-11-17 14:57 UTC, jtravee commented on docs/troubleshooting.md
> +This is a collection of information, which help you to troubleshoot if fleet is not working
```suggestion
This section contains commands and tips to troubleshoot Fleet.
```

2021-11-17 14:57 UTC, jtravee commented on docs/troubleshooting.md
> +You can check the status of the Fleet controller pods by running the below commands.
```suggestion
You can check the status of the Fleet controller pods by running the commands below:
```

2021-11-17 14:57 UTC, jtravee commented on docs/troubleshooting.md
> +If you see your GitJob complaining with this error
```suggestion
If your GitJob returns the error below, the problem may be that Fleet cannot access the Helm repo you specified in your [`fleet.yaml`](./gitrepo-structure.md):
```

2021-11-17 14:57 UTC, jtravee commented on docs/troubleshooting.md
> +This may indicate that fleet cannot access the helm repo you specified in your [`fleet.yaml`](./gitrepo-structure.md).
```suggestion
Perform the following steps to assess:
```

2021-11-17 14:57 UTC, jtravee commented on docs/troubleshooting.md
> +- check if your repo is accessible from your dev machine and you can actually download the helm chart
```suggestion
- Check that your repo is accessible from your dev machine, and that you can download the Helm chart successfully
```

2021-11-17 14:57 UTC, jtravee commented on docs/troubleshooting.md
> +- check if your credentials for the git repo are fine
```suggestion
- Check that your credentials for the git repo are correct
```

2021-11-17 14:57 UTC, jtravee commented on docs/troubleshooting.md
> +If you see your GitJob complaining with this error
```suggestion
If your GitJob returns the error below, you may have added the wrong certificate chain:
```

2021-11-17 14:57 UTC, jtravee commented on docs/troubleshooting.md
> +You may have added the wrong certificate chain. Please verify with
```suggestion
Please verify your certificate with the following command:
```

2021-11-17 14:57 UTC, jtravee commented on docs/gitrepo-add.md
> +see [Fleet deployment stuck in modified state](./troubleshooting.md)
```suggestion
see Fleet Troubleshooting section [here](./troubleshooting.md).
```

2021-11-18 08:05 UTC, papanito commented
Thanks for the review and the corrections

2021-11-18 14:56 UTC, jtravee approved these changes

2021-11-19 02:30 UTC, StrongMonkey approved these changes
This looks like and I like the structure now

2021-11-19 02:31 UTC, StrongMonkey commented
@nickgerace If you are good with the change we can merge it.

2021-11-19 05:40 UTC, papanito commented
Thanks to all.

2021-11-19 16:52 UTC, nickgerace approved these changes

2021-11-19 16:52 UTC, merged