Added note on ns creation behavior in Fleet bundles
rancher/fleet pull request #834
Opened 2022-06-22 20:41 UTC by jtravee

Closes #833

2022-06-23 19:32 UTC, btat requested changes

2022-06-23 20:16 UTC, jtravee commented on docs/namespaces.md
> +The `--create-namespace` flag in Fleet is responsible for the default behavior for namespace creation in bundles. Therefore, when deploying a Fleet bundle, the specified namespace will automatically
Updated as suggested.

2022-06-30 13:59 UTC, axeal approved these changes

2022-06-30 16:14 UTC, btat approved these changes

2022-06-30 16:15 UTC, merged